//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoHumano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleRolPagos
    {
        public int idDetalleRolPagos { get; set; }
        public int idRolPagos { get; set; }
        public int idEmpleado { get; set; }
        public decimal Sueldo { get; set; }
        public decimal HorasSuplementarias { get; set; }
        public decimal Bonificaciones { get; set; }
        public decimal FondoReserva { get; set; }
        public decimal Alimentacion { get; set; }
        public decimal OtrosIngresos { get; set; }
        public decimal AportacionIESS { get; set; }
        public decimal DescuentoAtrasos { get; set; }
        public decimal ImpuestoRenta { get; set; }
        public decimal PrestamoQuirografario { get; set; }
        public decimal PrestamoHipotecario { get; set; }
        public decimal Anticipos { get; set; }
        public decimal OtrosDescuentos { get; set; }
        public decimal SubIngresos { get; set; }
        public decimal SubDescuentos { get; set; }
        public decimal TotalIngresos { get; set; }
    
        public virtual Empleados Empleados { get; set; }
        public virtual RolPagos RolPagos { get; set; }
    }
}
