//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoHumano.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empleados
    {
        public Empleados()
        {
            this.DetalleRolPagos = new HashSet<DetalleRolPagos>();
            this.RolPagos = new HashSet<RolPagos>();
        }

        [Display(Name = "Id")]

        public int idEmpleados { get; set; }
        [CedulaEcuatoriana]
        [Display(Name = "Cedula")]
        public string Cedula { get; set; }
        public string Nombres { get; set; }
        [Display(Name = "Tipo de Contrato")]
        public string TipoContrato { get; set; }
        public string Cargo { get; set; }
        public bool Estado { get; set; }
        [Display(Name = "Fecha de Entrada")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime FechaEntrada { get; set; }
        [Display(Name = "Fecha de Salida")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaSalida { get; set; }
        public decimal Sueldo { get; set; }
        [Display(Name = "Horas Suplementarias")]
        public decimal HorasSuplementarias { get; set; }
        [Display(Name = "Dias Trabajados")]
        public int DiasTrabajados { get; set; }
        public decimal Bonificaciones { get; set; }
        public decimal FondoReserva { get; set; }
        public decimal Alimentacion { get; set; }
        [Display(Name = "Otros Ingresos")]
        public decimal OtrosIngresos { get; set; }
        [Display(Name = "Minutos de Atraso")]
        public Nullable<int> MinutosAtraso { get; set; }
        [Display(Name = "Valor del Minuto")]
        public Nullable<decimal> ValorMinuto { get; set; }
        [Display(Name = "Descuento por Atrasos")]
        public Nullable<decimal> descuentoAtrasos { get; set; }
        [Display(Name = "Aportación al IESS 9.45%")]
        public Nullable<decimal> AportacionIESS { get; set; }
        [Display(Name = "Impuesto a la Renta ")]
        public Nullable<decimal> ImpuestoRenta { get; set; }
        [Display(Name = "Prestamo Hipotecario")]
        public Nullable<decimal> PrestamoHipotecario { get; set; }
        [Display(Name = "Prestamo Quirofano")]
        public Nullable<decimal> PrestamoQuirografario { get; set; }
        public Nullable<decimal> Anticipos { get; set; }
        public Nullable<decimal> Seguro { get; set; }
        [Display(Name = "Otros Descuentos")]
        public Nullable<decimal> OtrosDescuentos { get; set; }
        public Nullable<decimal> Prestamos { get; set; }
    
        public virtual ICollection<DetalleRolPagos> DetalleRolPagos { get; set; }
        public virtual ICollection<RolPagos> RolPagos { get; set; }
    }
}
