//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TalentoHumano.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolPagos
    {
        public RolPagos()
        {
            this.DetalleRolPagos = new HashSet<DetalleRolPagos>();
        }
    
        public int idRolPagos { get; set; }
        public System.DateTime Fecha { get; set; }
        public int idEmpleado { get; set; }
    
        public virtual ICollection<DetalleRolPagos> DetalleRolPagos { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
